# Generated by Django 4.1.1 on 2022-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
